In [66]:
model = child_model()

# Reset the parameters 
model.mu = -1
model.eta2 = 2
model.eta3 = -0.5

model.beta = 0.99

# Step 2: Initialize value function and policy
n = model.n
#T = model.T
T = 20
V = np.nan + np.zeros([n, T])
D = np.nan + np.zeros([n, T])
D[:, T - 1] = 0
V[:, T - 1] = model.bellman(ev0 = np.zeros(n), output=1)
pk1 =  np.nan + np.zeros([n, T])
pk1[:, T-1] = 0

# Step 3: Backward induction
for t in range(T - 2, -1, -1):
    ev1, pk, d, value_0, value_1 = model.bellman(ev0 = V[:, t+1], output=3)
    V[:, t] = ev1  
    #print('V', V)
    pk1[:, t] = pk
    #print('pk', pk1)
    D[:, t] = d
    #print('D', D.round(0))
    #print(t,'0', value_0)
    #print(t,'1', value_1)

print(pk1.round(9))
#print(V.round(2))

#print(D.round(0))



[[0.68145266 0.68157663 0.6817755  0.68209096 0.68258509 0.68334811
  0.68450725 0.68623557 0.68875727 0.69234426 0.69729405 0.70387469
  0.71221702 0.72213308 0.73285458 0.74275084 0.74927789 0.74980613
  0.74389836 0.        ]
 [0.64880331 0.6488341  0.64888632 0.64897429 0.64912128 0.6493647
  0.64976364 0.65040975 0.65144179 0.6530639  0.65556512 0.65933419
  0.66485514 0.6726555  0.68315481 0.69632775 0.71107717 0.72435257
  0.73105858 0.        ]
 [0.64684599 0.64684975 0.64685654 0.6468688  0.64689083 0.64693024
  0.64700043 0.64712473 0.64734344 0.64772537 0.64838628 0.64951758
  0.65142831 0.65460178 0.65975898 0.66789438 0.68017258 0.69735836
  0.71781925 0.        ]
 [0.67661984 0.67661999 0.67662028 0.67662085 0.67662197 0.67662415
  0.67662841 0.67663675 0.67665305 0.67668492 0.67674722 0.67686903
  0.67710723 0.67757309 0.67848451 0.68026881 0.68376638 0.69063812
  0.70419191 0.        ]
 [0.73105858 0.73105858 0.73105858 0.73105858 0.73105858 0.73105858
  0.73105858 0.73

In [71]:
model = child_model()

V0=np.zeros(5)
tol = np.nan+np.zeros((10000))
for i in range(10000):
    V, pk = model.bellman(V0,output=2) # Do contraction step
    tol[i] = max(abs(V-V0)) # ToleranCe
    print(pk)
    V0 = V.copy() # Update V0



[0.52996405 0.52996405 0.52996405 0.52996405 0.52996405]
[0.54644819 0.52996405 0.51341428 0.49683504 0.52996405]
[0.55634642 0.52375142 0.49095335 0.47629858 0.52996405]
[0.5598836  0.51181086 0.46965548 0.46324265 0.52996405]
[0.55757043 0.49700749 0.451607   0.45479897 0.52996405]
[0.55087377 0.48166262 0.43705733 0.4492751  0.52996405]
[0.54149924 0.46716159 0.42563391 0.44563355 0.52996405]
[0.53089376 0.4541786  0.41680671 0.44322055 0.52996405]
[0.52009578 0.44294737 0.41005887 0.44161615 0.52996405]
[0.5097677  0.43345694 0.40494216 0.44054694 0.52996405]
[0.50028497 0.42557357 0.40108773 0.43983331 0.52996405]
[0.49182481 0.41911127 0.39820056 0.4393565  0.52996405]
[0.48443624 0.41387076 0.39604875 0.43903772 0.52996405]
[0.47809011 0.4096599  0.39445231 0.43882449 0.52996405]
[0.47271292 0.40630359 0.39327283 0.43868182 0.52996405]
[0.46820889 0.4036478  0.39240474 0.43858634 0.52996405]
[0.46447399 0.40156023 0.39176809 0.43852243 0.52996405]
[0.46140463 0.39992934 0.391302

In [57]:
np.exp(2)
1/(1+np.exp(4-5)) 

0.7310585786300049