In [109]:
# a. set magic 
%load_ext autoreload
%autoreload 2

# b. load packages 
import numpy as np

# c. local modules
from contracept_model import child_model

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [153]:
model = child_model()


In [144]:
# Reset the model parameters 
model.mu = -0.12
model.eta2 = .17
model.eta3 = -.05

model.beta = 0.99

# Step 2: Initialize value function and policy
n = model.n
T = model.T
V = np.nan + np.zeros([n, T])
V[:, T - 1] = life(N,model)
pnc1 =  np.nan + np.zeros([n, T])
pnc1[:, T-1] = 1

# Step 3: Backward induction
for t in range(T - 2, -1, -1):
    ev1, pnc = model.bellman(ev0 = V[:, t+1], output=2)
    V[:, t] = ev1  
    pnc1[:, t] = pnc


print(pnc1.round(3))
print(V.round(2))




[[0.521 0.524 0.528 0.532 0.536 0.54  0.544 0.548 0.552 0.556 0.559 0.562
  0.563 0.564 0.563 0.561 0.556 0.55  0.541 1.   ]
 [0.454 0.456 0.459 0.462 0.466 0.47  0.474 0.479 0.485 0.49  0.496 0.502
  0.509 0.515 0.521 0.526 0.529 0.532 0.532 1.   ]
 [0.429 0.43  0.431 0.433 0.435 0.437 0.44  0.443 0.447 0.451 0.456 0.462
  0.469 0.476 0.485 0.494 0.504 0.514 0.523 1.   ]
 [0.456 0.456 0.457 0.457 0.457 0.458 0.459 0.46  0.461 0.462 0.464 0.466
  0.469 0.473 0.477 0.483 0.491 0.501 0.514 1.   ]
 [0.53  0.53  0.53  0.53  0.53  0.53  0.53  0.53  0.53  0.53  0.53  0.53
  0.53  0.53  0.53  0.53  0.53  0.53  0.53  1.   ]]
[[11.77 11.27 10.76 10.23  9.69  9.13  8.56  7.97  7.36  6.74  6.1   5.44
   4.78  4.1   3.41  2.72  2.03  1.34  0.66  0.  ]
 [11.64 11.17 10.7  10.21  9.71  9.19  8.66  8.12  7.56  6.98  6.38  5.76
   5.13  4.47  3.79  3.08  2.36  1.63  0.88  0.12]
 [10.78 10.34  9.89  9.43  8.97  8.49  8.01  7.51  7.    6.48  5.95  5.4
   4.83  4.23  3.62  2.98  2.32  1.62  0.89  0.14]
 

In [134]:
model.bellman(ev0 = V[:, t+1], output=4)



[11.17665739 10.8028851   9.71888582  8.42876788  7.54257911]


(array([11.17665739, 10.8028851 ,  9.71888582,  8.42876788,  7.54257911]),
 array([0.49764955, 0.43210288, 0.41218683, 0.44742481, 0.52996405]),
 array([10.47879823,  9.96379353,  8.83260725,  7.62452111,  6.90763301]),
 array([10.48820009, 10.23707009,  9.1875397 ,  7.83560211,  6.78763301]))

In [139]:
np.log(np.exp(10.48820009-10.48820009))

0.0

In [141]:
np.log(np.exp(10.47879823-10.48820009))

-0.009401859999998746

In [154]:
model.sim_data([(0.5, 0.5, 0.5,0.5,0,5)])

TypeError: unsupported operand type(s) for -: 'int' and 'tuple'

In [119]:
model = child_model()

In [120]:
model.bellman(ev0 = , output=4)

[0.6349461 0.7549461 0.7749461 0.6949461 0.5149461]


(array([0.6349461, 0.7549461, 0.7749461, 0.6949461, 0.5149461]),
 array([0.52996405, 0.52996405, 0.52996405, 0.52996405, 0.52996405]),
 array([ 0.  ,  0.12,  0.14,  0.06, -0.12]),
 array([-1.20000000e-01,  1.38777878e-17,  2.00000000e-02, -6.00000000e-02,
        -2.40000000e-01]))

In [131]:
print(model.cost + model.beta * model.P1 @ ev0)
print(model.mu + model.cost + model.beta * model.P2 @ ev0)

[ 0.0470448  0.2454528  0.2458508  0.0482388 -0.237612 ]
[-0.11647164  0.11820006  0.15486176 -0.00648654 -0.357612  ]
