In [2]:
# a. set magic 
%load_ext autoreload
%autoreload 2

# b. load packages 
import numpy as np

# c. local modules
from newtest import child_model

In [13]:
model = child_model()

# Reset the modelameters 
model.mu = -0.12
model.eta2 = 0.15
model.eta3 = -0.5

model.beta = 0.99

# Step 2: Initialize value function and policy
n = model.n
#T = model.T
T = 20
V = np.nan + np.zeros([n, T])
D = np.nan + np.zeros([n, T])
D[:, T - 1] = 0
V[:, T - 1] = model.bellman(ev0 = np.zeros(n), output=1)
pcn1 =  np.nan + np.zeros([n, T])
pcn1[:, T-1] = 0

# Step 3: Backward induction
for t in range(T - 2, -1, -1):
    ev1, pcn = model.bellman(ev0 = V[:, t+1], output=2)
    V[:, t] = ev1  
    #print('V', V)
    pcn1[:, t] = pcn
    #print('pk', pk1)
    #D[:, t] = d
    #print('D', D.round(0))
    #print(t,'0', value_0)
    #print(t,'1', value_1)

print(pcn1.round(3))
#print(V.round(2))

#print(D.round(0))



[[0.398 0.401 0.405 0.409 0.414 0.42  0.426 0.433 0.441 0.45  0.46  0.47
  0.48  0.489 0.497 0.502 0.502 0.497 0.487 0.   ]
 [0.329 0.331 0.333 0.336 0.339 0.343 0.348 0.353 0.36  0.368 0.377 0.387
  0.399 0.412 0.426 0.44  0.454 0.464 0.47  0.   ]
 [0.318 0.319 0.32  0.32  0.322 0.323 0.325 0.328 0.331 0.335 0.34  0.347
  0.355 0.365 0.378 0.393 0.411 0.432 0.454 0.   ]
 [0.369 0.369 0.369 0.369 0.369 0.369 0.37  0.37  0.371 0.372 0.373 0.375
  0.377 0.38  0.385 0.392 0.401 0.416 0.437 0.   ]
 [0.47  0.47  0.47  0.47  0.47  0.47  0.47  0.47  0.47  0.47  0.47  0.47
  0.47  0.47  0.47  0.47  0.47  0.47  0.47  0.   ]]


In [71]:
model = child_model()

V0=np.zeros(5)
tol = np.nan+np.zeros((10000))
for i in range(10000):
    V, pk = model.bellman(V0,output=2) # Do contraction step
    tol[i] = max(abs(V-V0)) # ToleranCe
    print(pk)
    V0 = V.copy() # Update V0



[0.52996405 0.52996405 0.52996405 0.52996405 0.52996405]
[0.54644819 0.52996405 0.51341428 0.49683504 0.52996405]
[0.55634642 0.52375142 0.49095335 0.47629858 0.52996405]
[0.5598836  0.51181086 0.46965548 0.46324265 0.52996405]
[0.55757043 0.49700749 0.451607   0.45479897 0.52996405]
[0.55087377 0.48166262 0.43705733 0.4492751  0.52996405]
[0.54149924 0.46716159 0.42563391 0.44563355 0.52996405]
[0.53089376 0.4541786  0.41680671 0.44322055 0.52996405]
[0.52009578 0.44294737 0.41005887 0.44161615 0.52996405]
[0.5097677  0.43345694 0.40494216 0.44054694 0.52996405]
[0.50028497 0.42557357 0.40108773 0.43983331 0.52996405]
[0.49182481 0.41911127 0.39820056 0.4393565  0.52996405]
[0.48443624 0.41387076 0.39604875 0.43903772 0.52996405]
[0.47809011 0.4096599  0.39445231 0.43882449 0.52996405]
[0.47271292 0.40630359 0.39327283 0.43868182 0.52996405]
[0.46820889 0.4036478  0.39240474 0.43858634 0.52996405]
[0.46447399 0.40156023 0.39176809 0.43852243 0.52996405]
[0.46140463 0.39992934 0.391302

UnboundLocalError: local variable 'life' referenced before assignment

In [23]:
def utility(N, d, model):
    return model.eta2 * N + model.eta3 * N**2 + model.mu * d
def life(N,model):
    life_value = 0
    for t in range(1,41):
        life_value += model.beta**t *(model.eta2 * N + model.eta3 * N**2)
        return life_value

def v_last_period(N,d,model):
    return utility(N, d, model) + life(N,model)



In [25]:
N = np.arange(0,5)
life(N,model)

-13.365

In [ ]:
def v(c,m,par,v_plus_interp):
    
    # a. expected value
    v_plus = 0.0
    for d in [0,1]:
        
        # i. next period cash-on-hand
        
        m_plus = (1+par.r)*a + y
        
        # ii. next-period values
        v_plus_now = v_plus_interp([m_plus])[0]
        
        # iii. probability weighted sum
        v_plus += p*v_plus_now
    
    # b. total value
    return utility(d,par) + par.beta*v_plus

In [ ]:
def solve_last_period(par):

    # a. allocate
    N_grid = np.linspace(0,4,5)
    v_func = np.empty(par.Nm)
    d_func = np.empty(par.Nm)

    # b. solve
    for t,N in enumerate(N_grid):

        # i. objective
        obj = lambda x: -v_last_period(x[0],d,par)

        # ii. optimizer
        x0 = m/2 # initial value
        result = optimize.minimize(obj,[x0],method='L-BFGS-B',bounds=((1e-8,m),))

        # iii. save
        v_func[i] = -result.fun
        c_func[i] = result.x
        
    return m_grid,v_func,c_func

In [57]:
np.exp(2)
1/(1+np.exp(4-5)) 

0.7310585786300049